# Docker Compose for CI testing - no version needed

services:
  bookstack-db:
    image: mariadb:10.5
    environment:
      - MYSQL_ROOT_PASSWORD=bookstackpass
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=bookstackpass
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3306:3306"

  bookstack:
    image: lscr.io/linuxserver/bookstack:${BOOKSTACK_VERSION:-latest}
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - MAIL_DRIVER=log
      - APP_DEBUG=false
    ports:
      - "6875:80"
    depends_on:
      bookstack-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/login"]
      interval: 10s
      timeout: 5s
      retries: 10